//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.2-7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2015.09.21 at 10:40:02 AM PDT
//

package edu.scripps.yates.pcq.xgmml.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="att" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="graphics">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="att" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="node" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="att" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="graphics">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="att" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="h" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="w" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="outline" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="fill" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="edge">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="att" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="graphics">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="att" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="fill" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="source" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="directed" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "att", "graphics", "node", "edge" })
@XmlRootElement(name = "graph")
public class Graph {

	@XmlElement(required = true)
	protected List<Graph.Att> att;
	@XmlElement(required = true)
	protected Graph.Graphics graphics;
	@XmlElement(required = true)
	protected List<Graph.Node> node;
	@XmlElement(required = true)
	protected List<Graph.Edge> edge;
	@XmlAttribute(name = "id")
	protected Integer id;
	@XmlAttribute(name = "label")
	protected String label;
	@XmlAttribute(name = "directed")
	protected Integer directed;

	/**
	 * Gets the value of the att property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the att property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 *
	 * <pre>
	 * getAtt().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Graph.Att
	 * }
	 *
	 *
	 */
	public List<Graph.Att> getAtt() {
		if (att == null) {
			att = new ArrayList<Graph.Att>();
		}
		return att;
	}

	/**
	 * Gets the value of the graphics property.
	 *
	 * @return possible object is {@link Graph.Graphics }
	 *
	 */
	public Graph.Graphics getGraphics() {
		return graphics;
	}

	/**
	 * Sets the value of the graphics property.
	 *
	 * @param value
	 *            allowed object is {@link Graph.Graphics }
	 *
	 */
	public void setGraphics(Graph.Graphics value) {
		graphics = value;
	}

	/**
	 * Gets the value of the node property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the node property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 *
	 * <pre>
	 * getNode().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Graph.Node }
	 *
	 *
	 */
	public List<Graph.Node> getNode() {
		if (node == null) {
			node = new ArrayList<Graph.Node>();
		}
		return node;
	}

	/**
	 * Gets the value of the edge property.
	 *
	 * @return possible object is {@link Graph.Edge }
	 *
	 */
	public List<Graph.Edge> getEdge() {
		if (edge == null) {
			edge = new ArrayList<Graph.Edge>();
		}
		return edge;
	}

	/**
	 * Gets the value of the id property.
	 *
	 * @return possible object is {@link Integer }
	 *
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 *
	 * @param value
	 *            allowed object is {@link Integer }
	 *
	 */
	public void setId(Integer value) {
		id = value;
	}

	/**
	 * Gets the value of the label property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getLabel() {
		return label;
	}

	/**
	 * Sets the value of the label property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setLabel(String value) {
		label = value;
	}

	/**
	 * Gets the value of the directed property.
	 *
	 * @return possible object is {@link Integer }
	 *
	 */
	public Integer getDirected() {
		return directed;
	}

	/**
	 * Sets the value of the directed property.
	 *
	 * @param value
	 *            allowed object is {@link Integer }
	 *
	 */
	public void setDirected(Integer value) {
		directed = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 *
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 *
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "")
	public static class Att {

		@XmlAttribute(name = "name")
		protected String name;
		@XmlAttribute(name = "value")
		protected String value;
		@XmlAttribute(name = "type")
		protected String type;

		/**
		 * Gets the value of the name property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getName() {
			return name;
		}

		/**
		 * Sets the value of the name property.
		 *
		 * @param value
		 *            allowed object is {@link String }
		 *
		 */
		public void setName(String value) {
			name = value;
		}

		/**
		 * Gets the value of the value property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getValue() {
			return value;
		}

		/**
		 * Sets the value of the value property.
		 *
		 * @param value
		 *            allowed object is {@link String }
		 *
		 */
		public void setValue(String value) {
			this.value = value;
		}

		/**
		 * Gets the value of the type property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getType() {
			return type;
		}

		/**
		 * Sets the value of the type property.
		 *
		 * @param value
		 *            allowed object is {@link String }
		 *
		 */
		public void setType(String value) {
			type = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 *
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 *
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="att" maxOccurs="unbounded">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="graphics">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="att" maxOccurs="unbounded">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                           &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                 &lt;/sequence>
	 *                 &lt;attribute name="fill" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}int" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
	 *       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *       &lt;attribute name="source" type="{http://www.w3.org/2001/XMLSchema}int" />
	 *       &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}int" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "att", "graphics" })
	public static class Edge {

		@XmlElement(required = true)
		protected List<Graph.Edge.Att> att;
		@XmlElement(required = true)
		protected Graph.Edge.Graphics graphics;
		@XmlAttribute(name = "id")
		protected Integer id;
		@XmlAttribute(name = "label")
		protected String label;
		@XmlAttribute(name = "source")
		protected String source;
		@XmlAttribute(name = "target")
		protected String target;

		/**
		 * Gets the value of the att property.
		 *
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the att property.
		 *
		 * <p>
		 * For example, to add a new item, do as follows:
		 *
		 * <pre>
		 * getAtt().add(newItem);
		 * </pre>
		 *
		 *
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Graph.Edge.Att }
		 *
		 *
		 */
		public List<Graph.Edge.Att> getAtt() {
			if (att == null) {
				att = new ArrayList<Graph.Edge.Att>();
			}
			return att;
		}

		/**
		 * Gets the value of the graphics property.
		 *
		 * @return possible object is {@link Graph.Edge.Graphics }
		 *
		 */
		public Graph.Edge.Graphics getGraphics() {
			return graphics;
		}

		/**
		 * Sets the value of the graphics property.
		 *
		 * @param value
		 *            allowed object is {@link Graph.Edge.Graphics }
		 *
		 */
		public void setGraphics(Graph.Edge.Graphics value) {
			graphics = value;
		}

		/**
		 * Gets the value of the id property.
		 *
		 * @return possible object is {@link Integer }
		 *
		 */
		public Integer getId() {
			return id;
		}

		/**
		 * Sets the value of the id property.
		 *
		 * @param value
		 *            allowed object is {@link Integer }
		 *
		 */
		public void setId(Integer value) {
			id = value;
		}

		/**
		 * Gets the value of the label property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getLabel() {
			return label;
		}

		/**
		 * Sets the value of the label property.
		 *
		 * @param value
		 *            allowed object is {@link String }
		 *
		 */
		public void setLabel(String value) {
			label = value;
		}

		/**
		 * Gets the value of the source property.
		 *
		 * @return possible object is {@link Integer }
		 *
		 */
		public String getSource() {
			return source;
		}

		/**
		 * Sets the value of the source property.
		 *
		 * @param value
		 *            allowed object is {@link Integer }
		 *
		 */
		public void setSource(String value) {
			source = value;
		}

		/**
		 * Gets the value of the target property.
		 *
		 * @return possible object is {@link Integer }
		 *
		 */
		public String getTarget() {
			return target;
		}

		/**
		 * Sets the value of the target property.
		 *
		 * @param value
		 *            allowed object is {@link Integer }
		 *
		 */
		public void setTarget(String value) {
			target = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 *
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 *
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 *
		 *
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "")
		public static class Att {

			@XmlAttribute(name = "name")
			protected String name;
			@XmlAttribute(name = "value")
			protected String value;
			@XmlAttribute(name = "type")
			protected String type;

			/**
			 * Gets the value of the name property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getName() {
				return name;
			}

			/**
			 * Sets the value of the name property.
			 *
			 * @param value
			 *            allowed object is {@link String }
			 *
			 */
			public void setName(String value) {
				name = value;
			}

			/**
			 * Gets the value of the value property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getValue() {
				return value;
			}

			/**
			 * Sets the value of the value property.
			 *
			 * @param value
			 *            allowed object is {@link String }
			 *
			 */
			public void setValue(String value) {
				this.value = value;
			}

			/**
			 * Gets the value of the type property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getType() {
				return type;
			}

			/**
			 * Sets the value of the type property.
			 *
			 * @param value
			 *            allowed object is {@link String }
			 *
			 */
			public void setType(String value) {
				type = value;
			}

		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 *
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 *
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="att" maxOccurs="unbounded">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *       &lt;/sequence>
		 *       &lt;attribute name="fill" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}int" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 *
		 *
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "att" })
		public static class Graphics {

			@XmlElement(required = true)
			protected List<Graph.Edge.Graphics.Att> att;
			@XmlAttribute(name = "fill")
			protected String fill;
			@XmlAttribute(name = "width")
			protected Integer width;

			/**
			 * Gets the value of the att property.
			 *
			 * <p>
			 * This accessor method returns a reference to the live list, not a
			 * snapshot. Therefore any modification you make to the returned
			 * list will be present inside the JAXB object. This is why there is
			 * not a <CODE>set</CODE> method for the att property.
			 *
			 * <p>
			 * For example, to add a new item, do as follows:
			 *
			 * <pre>
			 * getAtt().add(newItem);
			 * </pre>
			 *
			 *
			 * <p>
			 * Objects of the following type(s) are allowed in the list
			 * {@link Graph.Edge.Graphics.Att }
			 *
			 *
			 */
			public List<Graph.Edge.Graphics.Att> getAtt() {
				if (att == null) {
					att = new ArrayList<Graph.Edge.Graphics.Att>();
				}
				return att;
			}

			/**
			 * Gets the value of the fill property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getFill() {
				return fill;
			}

			/**
			 * Sets the value of the fill property.
			 *
			 * @param value
			 *            allowed object is {@link String }
			 *
			 */
			public void setFill(String value) {
				fill = value;
			}

			/**
			 * Gets the value of the width property.
			 *
			 * @return possible object is {@link Integer }
			 *
			 */
			public Integer getWidth() {
				return width;
			}

			/**
			 * Sets the value of the width property.
			 *
			 * @param value
			 *            allowed object is {@link Integer }
			 *
			 */
			public void setWidth(Integer value) {
				width = value;
			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 *
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 *
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
			 *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
			 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 *
			 *
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "")
			public static class Att {

				@XmlAttribute(name = "name")
				protected String name;
				@XmlAttribute(name = "value")
				protected String value;
				@XmlAttribute(name = "type")
				protected String type;

				/**
				 * Gets the value of the name property.
				 *
				 * @return possible object is {@link String }
				 *
				 */
				public String getName() {
					return name;
				}

				/**
				 * Sets the value of the name property.
				 *
				 * @param value
				 *            allowed object is {@link String }
				 *
				 */
				public void setName(String value) {
					name = value;
				}

				/**
				 * Gets the value of the value property.
				 *
				 * @return possible object is {@link String }
				 *
				 */
				public String getValue() {
					return value;
				}

				/**
				 * Sets the value of the value property.
				 *
				 * @param value
				 *            allowed object is {@link String }
				 *
				 */
				public void setValue(String value) {
					this.value = value;
				}

				/**
				 * Gets the value of the type property.
				 *
				 * @return possible object is {@link String }
				 *
				 */
				public String getType() {
					return type;
				}

				/**
				 * Sets the value of the type property.
				 *
				 * @param value
				 *            allowed object is {@link String }
				 *
				 */
				public void setType(String value) {
					type = value;
				}

			}

		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 *
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 *
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="att" maxOccurs="unbounded">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}double" />
	 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "att" })
	public static class Graphics {

		@XmlElement(required = true)
		protected List<Graph.Graphics.Att> att;

		/**
		 * Gets the value of the att property.
		 *
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the att property.
		 *
		 * <p>
		 * For example, to add a new item, do as follows:
		 *
		 * <pre>
		 * getAtt().add(newItem);
		 * </pre>
		 *
		 *
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Graph.Graphics.Att }
		 *
		 *
		 */
		public List<Graph.Graphics.Att> getAtt() {
			if (att == null) {
				att = new ArrayList<Graph.Graphics.Att>();
			}
			return att;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 *
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 *
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}double" />
		 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 *
		 *
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "")
		public static class Att {

			@XmlAttribute(name = "name")
			protected String name;
			@XmlAttribute(name = "value")
			protected String value;
			@XmlAttribute(name = "type")
			protected String type;

			/**
			 * Gets the value of the name property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getName() {
				return name;
			}

			/**
			 * Sets the value of the name property.
			 *
			 * @param value
			 *            allowed object is {@link String }
			 *
			 */
			public void setName(String value) {
				name = value;
			}

			/**
			 * Gets the value of the value property.
			 *
			 * @return possible object is {@link Double }
			 *
			 */
			public String getValue() {
				return value;
			}

			/**
			 * Sets the value of the value property.
			 *
			 * @param value
			 *            allowed object is {@link Double }
			 *
			 */
			public void setValue(String value) {
				this.value = value;
			}

			/**
			 * Gets the value of the type property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getType() {
				return type;
			}

			/**
			 * Sets the value of the type property.
			 *
			 * @param value
			 *            allowed object is {@link String }
			 *
			 */
			public void setType(String value) {
				type = value;
			}

		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 *
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 *
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="att" maxOccurs="unbounded">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="graphics">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="att" maxOccurs="unbounded">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                           &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                 &lt;/sequence>
	 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="h" type="{http://www.w3.org/2001/XMLSchema}int" />
	 *                 &lt;attribute name="w" type="{http://www.w3.org/2001/XMLSchema}int" />
	 *                 &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}int" />
	 *                 &lt;attribute name="outline" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="fill" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
	 *       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "att", "graphics" })
	public static class Node {

		@XmlElement(required = true)
		protected List<Graph.Node.Att> att;
		@XmlElement(required = true)
		protected Graph.Node.Graphics graphics;
		@XmlAttribute(name = "id")
		protected String id;
		@XmlAttribute(name = "label")
		protected String label;

		/**
		 * Gets the value of the att property.
		 *
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the att property.
		 *
		 * <p>
		 * For example, to add a new item, do as follows:
		 *
		 * <pre>
		 * getAtt().add(newItem);
		 * </pre>
		 *
		 *
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Graph.Node.Att }
		 *
		 *
		 */
		public List<Graph.Node.Att> getAtt() {
			if (att == null) {
				att = new ArrayList<Graph.Node.Att>();
			}
			return att;
		}

		/**
		 * Gets the value of the graphics property.
		 *
		 * @return possible object is {@link Graph.Node.Graphics }
		 *
		 */
		public Graph.Node.Graphics getGraphics() {
			return graphics;
		}

		/**
		 * Sets the value of the graphics property.
		 *
		 * @param value
		 *            allowed object is {@link Graph.Node.Graphics }
		 *
		 */
		public void setGraphics(Graph.Node.Graphics value) {
			graphics = value;
		}

		/**
		 * Gets the value of the id property.
		 *
		 * @return possible object is {@link Integer }
		 *
		 */
		public String getId() {
			return id;
		}

		/**
		 * Sets the value of the id property.
		 *
		 * @param value
		 *            allowed object is {@link Integer }
		 *
		 */
		public void setId(String value) {
			id = value;
		}

		/**
		 * Gets the value of the label property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getLabel() {
			return label;
		}

		/**
		 * Sets the value of the label property.
		 *
		 * @param value
		 *            allowed object is {@link String }
		 *
		 */
		public void setLabel(String value) {
			label = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 *
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 *
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 *
		 *
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "")
		public static class Att {

			@XmlAttribute(name = "name")
			protected String name;
			@XmlAttribute(name = "value")
			protected String value;
			@XmlAttribute(name = "type")
			protected String type;

			/**
			 * Gets the value of the name property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getName() {
				return name;
			}

			/**
			 * Sets the value of the name property.
			 *
			 * @param value
			 *            allowed object is {@link String }
			 *
			 */
			public void setName(String value) {
				name = value;
			}

			/**
			 * Gets the value of the value property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getValue() {
				return value;
			}

			/**
			 * Sets the value of the value property.
			 *
			 * @param value
			 *            allowed object is {@link String }
			 *
			 */
			public void setValue(String value) {
				this.value = value;
			}

			/**
			 * Gets the value of the type property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getType() {
				return type;
			}

			/**
			 * Sets the value of the type property.
			 *
			 * @param value
			 *            allowed object is {@link String }
			 *
			 */
			public void setType(String value) {
				type = value;
			}

		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 *
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 *
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="att" maxOccurs="unbounded">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *       &lt;/sequence>
		 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="h" type="{http://www.w3.org/2001/XMLSchema}int" />
		 *       &lt;attribute name="w" type="{http://www.w3.org/2001/XMLSchema}int" />
		 *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}int" />
		 *       &lt;attribute name="outline" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="fill" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 *
		 *
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "att" })
		public static class Graphics {

			@XmlElement(required = true)
			protected List<Graph.Node.Graphics.Att> att;
			@XmlAttribute(name = "type")
			protected String type;
			@XmlAttribute(name = "h")
			protected Integer h;
			@XmlAttribute(name = "w")
			protected Integer w;
			@XmlAttribute(name = "width")
			protected Integer width;
			@XmlAttribute(name = "outline")
			protected String outline;
			@XmlAttribute(name = "fill")
			protected String fill;

			/**
			 * Gets the value of the att property.
			 *
			 * <p>
			 * This accessor method returns a reference to the live list, not a
			 * snapshot. Therefore any modification you make to the returned
			 * list will be present inside the JAXB object. This is why there is
			 * not a <CODE>set</CODE> method for the att property.
			 *
			 * <p>
			 * For example, to add a new item, do as follows:
			 *
			 * <pre>
			 * getAtt().add(newItem);
			 * </pre>
			 *
			 *
			 * <p>
			 * Objects of the following type(s) are allowed in the list
			 * {@link Graph.Node.Graphics.Att }
			 *
			 *
			 */
			public List<Graph.Node.Graphics.Att> getAtt() {
				if (att == null) {
					att = new ArrayList<Graph.Node.Graphics.Att>();
				}
				return att;
			}

			/**
			 * Gets the value of the type property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getType() {
				return type;
			}

			/**
			 * Sets the value of the type property.
			 *
			 * @param value
			 *            allowed object is {@link String }
			 *
			 */
			public void setType(String value) {
				type = value;
			}

			/**
			 * Gets the value of the h property.
			 *
			 * @return possible object is {@link Integer }
			 *
			 */
			public Integer getH() {
				return h;
			}

			/**
			 * Sets the value of the h property.
			 *
			 * @param value
			 *            allowed object is {@link Integer }
			 *
			 */
			public void setH(Integer value) {
				h = value;
			}

			/**
			 * Gets the value of the w property.
			 *
			 * @return possible object is {@link Integer }
			 *
			 */
			public Integer getW() {
				return w;
			}

			/**
			 * Sets the value of the w property.
			 *
			 * @param value
			 *            allowed object is {@link Integer }
			 *
			 */
			public void setW(Integer value) {
				w = value;
			}

			/**
			 * Gets the value of the width property.
			 *
			 * @return possible object is {@link Integer }
			 *
			 */
			public Integer getWidth() {
				return width;
			}

			/**
			 * Sets the value of the width property.
			 *
			 * @param value
			 *            allowed object is {@link Integer }
			 *
			 */
			public void setWidth(Integer value) {
				width = value;
			}

			/**
			 * Gets the value of the outline property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getOutline() {
				return outline;
			}

			/**
			 * Sets the value of the outline property.
			 *
			 * @param value
			 *            allowed object is {@link String }
			 *
			 */
			public void setOutline(String value) {
				outline = value;
			}

			/**
			 * Gets the value of the fill property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getFill() {
				return fill;
			}

			/**
			 * Sets the value of the fill property.
			 *
			 * @param value
			 *            allowed object is {@link String }
			 *
			 */
			public void setFill(String value) {
				fill = value;
			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 *
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 *
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
			 *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
			 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 *
			 *
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "")
			public static class Att {

				@XmlAttribute(name = "name")
				protected String name;
				@XmlAttribute(name = "value")
				protected String value;
				@XmlAttribute(name = "type")
				protected String type;

				/**
				 * Gets the value of the name property.
				 *
				 * @return possible object is {@link String }
				 *
				 */
				public String getName() {
					return name;
				}

				/**
				 * Sets the value of the name property.
				 *
				 * @param value
				 *            allowed object is {@link String }
				 *
				 */
				public void setName(String value) {
					name = value;
				}

				/**
				 * Gets the value of the value property.
				 *
				 * @return possible object is {@link String }
				 *
				 */
				public String getValue() {
					return value;
				}

				/**
				 * Sets the value of the value property.
				 *
				 * @param value
				 *            allowed object is {@link String }
				 *
				 */
				public void setValue(String value) {
					this.value = value;
				}

				/**
				 * Gets the value of the type property.
				 *
				 * @return possible object is {@link String }
				 *
				 */
				public String getType() {
					return type;
				}

				/**
				 * Sets the value of the type property.
				 *
				 * @param value
				 *            allowed object is {@link String }
				 *
				 */
				public void setType(String value) {
					type = value;
				}

			}

		}

	}

}
