//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.21 at 10:40:02 AM PDT 
//


package edu.scripps.yates.pcq.xgmml.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.scripps.yates.proteinclusters.xgmml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.scripps.yates.proteinclusters.xgmml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Graph.Edge.Att }
     * 
     */
    public Graph.Edge.Att createGraphEdgeAtt() {
        return new Graph.Edge.Att();
    }

    /**
     * Create an instance of {@link Graph.Att }
     * 
     */
    public Graph.Att createGraphAtt() {
        return new Graph.Att();
    }

    /**
     * Create an instance of {@link Graph }
     * 
     */
    public Graph createGraph() {
        return new Graph();
    }

    /**
     * Create an instance of {@link Graph.Graphics.Att }
     * 
     */
    public Graph.Graphics.Att createGraphGraphicsAtt() {
        return new Graph.Graphics.Att();
    }

    /**
     * Create an instance of {@link Graph.Node.Graphics }
     * 
     */
    public Graph.Node.Graphics createGraphNodeGraphics() {
        return new Graph.Node.Graphics();
    }

    /**
     * Create an instance of {@link Graph.Edge.Graphics.Att }
     * 
     */
    public Graph.Edge.Graphics.Att createGraphEdgeGraphicsAtt() {
        return new Graph.Edge.Graphics.Att();
    }

    /**
     * Create an instance of {@link Graph.Edge.Graphics }
     * 
     */
    public Graph.Edge.Graphics createGraphEdgeGraphics() {
        return new Graph.Edge.Graphics();
    }

    /**
     * Create an instance of {@link Graph.Node.Att }
     * 
     */
    public Graph.Node.Att createGraphNodeAtt() {
        return new Graph.Node.Att();
    }

    /**
     * Create an instance of {@link Graph.Graphics }
     * 
     */
    public Graph.Graphics createGraphGraphics() {
        return new Graph.Graphics();
    }

    /**
     * Create an instance of {@link Graph.Node }
     * 
     */
    public Graph.Node createGraphNode() {
        return new Graph.Node();
    }

    /**
     * Create an instance of {@link Graph.Edge }
     * 
     */
    public Graph.Edge createGraphEdge() {
        return new Graph.Edge();
    }

    /**
     * Create an instance of {@link Graph.Node.Graphics.Att }
     * 
     */
    public Graph.Node.Graphics.Att createGraphNodeGraphicsAtt() {
        return new Graph.Node.Graphics.Att();
    }

}
